# Triggers
trigger:
  branches:
    include:
      - 'main'
      - 'release-*'
pr:
  autoCancel: true
  branches:
    include:
      - '*'

# Stages
stages:
  - stage: say_hello
    displayName: Say hello
    jobs:
      - job: 'hello'
        displayName: 'Build'
        # Set timeout for jobs
        timeoutInMinutes: 60
        # Base system
        pool:
          vmImage: 'Ubuntu-18.04'
        # Pipeline steps
        steps:
          - bash: "echo \"hello\""