# Triggers
trigger:
  branches:
    include:
      - 'main'
      - 'release-*'
  tags:
    include:
      - '*'
pr:
  autoCancel: true
  branches:
    include:
      - '*'

jobs:
  - job: 'main_branch_build'
    displayName: 'Build'
    # Set timeout for jobs
    timeoutInMinutes: 60
    # Base system
    pool:
      vmImage: 'Ubuntu-18.04'
    # Pipeline steps
    steps:
      - task: Cache@2
        inputs:
          key: '"kafka_binaries"'
          path: images
        displayName: Kafka Binaries cache
      - bash: make prepare
        displayName: "Download kafka"
      - bash: make docker_build
        displayName: "Build images"
      - bash: make docker_tag_push
        condition: and(succeeded(), or(eq(variables['build.sourceBranch'], 'refs/heads/main'), startsWith(variables['build.sourceBranch'], 'refs/tags/')))
        displayName: "Tag and push images"
        env:
          QUAY_USER: $(QUAY_USER)
          QUAY_PASS: $(QUAY_PASS)